name: Latest Dev.To post
on:
  schedule:
    # Runs every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest Dev.To post
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in Dev.To posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "DEVTO-ARTICLE"
          feed_list: "https://dev.to/feed/anthonyzhang220"
          template : '<p><a href="$url">$title</a></p>'
